/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include "stm32f767xx.h"

const uint32_t my_const_data_1 = 100;
const uint32_t my_const_data_2 = 50;


void delayMs(uint32_t ms);
uint32_t mydata = 0x55555555;

int main(void)
{
    /* Loop forever */
    RCC->AHB1ENR |= 0x2;

    GPIOB->MODER &= ~(0x3 << 14);
    GPIOB->MODER|= (1<<14);

    //GPIOB->MODER &= ~(0x3 << 28);
    //GPIOB->MODER |= (1 << 28);
    //printf("Hello World!");
	for(;;)
	{
        GPIOB->ODR |= (1 << 7);
	    //GPIOB->ODR |= (1 << 14);
	    delayMs(100);
        GPIOB->ODR &= ~(1 << 7);
	    //GPIOB->ODR &= ~(1 << 14);
	    delayMs(100);
	}
}

void delayMs(uint32_t ms)
{
    for (; ms > 0; ms--)
    {
        for (int i=0; i < 3195; i++);
    }
}
